import mdx from "@astrojs/mdx";
import { unified } from "@astrojs/markdown-remark";
import sitemap from "@astrojs/sitemap";
import icon from "astro-icon";
import { defineConfig } from "astro/config";
import mermaid from "astro-mermaid";

export default defineConfig({
  site: "https://vivekraman.dev",
  base: "/",
  output: "static",
  /** Match static server’s directory URLs so internal links don’t chain redirects (better for view transitions). */
  trailingSlash: "always",
  integrations: [
    mdx(),
    sitemap(),
    mermaid({
      theme: "forest",
      autoTheme: true,
      mermaidConfig: {},
    }),
    icon({
      include: {
        lucide: ["arrow-right"],
        "simple-icons": ["langchain", "posthog"],
        "skill-icons": [
          "appwrite",
          "astro",
          "aws-light",
          "aws-dark",
          "bash-light",
          "bash-dark",
          "blender-light",
          "blender-dark",
          "c",
          "cpp",
          "cs",
          "cloudflare-light",
          "cloudflare-dark",
          "django",
          "elasticsearch-light",
          "elasticsearch-dark",
          "expressjs-light",
          "expressjs-dark",
          "fastapi",
          "figma-light",
          "figma-dark",
          "flask-light",
          "flask-dark",
          "flutter-light",
          "flutter-dark",
          "gcp-light",
          "gcp-dark",
          "githubactions-light",
          "githubactions-dark",
          "gradle-light",
          "gradle-dark",
          "grafana-light",
          "grafana-dark",
          "java-light",
          "java-dark",
          "javascript",
          "jenkins-light",
          "jenkins-dark",
          "kafka",
          "kubernetes",
          "maven-light",
          "maven-dark",
          "mongodb",
          "mysql-light",
          "mysql-dark",
          "nextjs-light",
          "nextjs-dark",
          "nodejs-light",
          "nodejs-dark",
          "nginx",
          "postgresql-light",
          "postgresql-dark",
          "prometheus",
          "python-light",
          "python-dark",
          "rabbitmq-light",
          "rabbitmq-dark",
          "react-light",
          "react-dark",
          "redis-light",
          "redis-dark",
          "regex-light",
          "regex-dark",
          "spring-light",
          "spring-dark",
          "svelte",
          "tensorflow-light",
          "tensorflow-dark",
          "typescript",
          "unity-light",
          "unity-dark",
          "vercel-light",
          "vercel-dark",
          "vuejs-light",
          "vuejs-dark",
          "xd",
        ],
      },
    }),
  ],
  markdown: {
    processor: unified(),
    shikiConfig: {
      themes: {
        light: "catppuccin-latte",
        dark: "catppuccin-mocha",
      },
      defaultColor: "light-dark()",
      langs: [],
      wrap: true,
    },
  },
});
