// Generated by scripts/build-pokemon-region-sprites.mjs. Do not edit manually.
export type FormSpriteLocation = { sheet: string; slot: number };

export const formSpriteManifest: Record<string, FormSpriteLocation> = {
  "19:alola": {
    "sheet": "alola",
    "slot": 88
  },
  "20:alola": {
    "sheet": "alola",
    "slot": 89
  },
  "26:alola": {
    "sheet": "alola",
    "slot": 90
  },
  "27:alola": {
    "sheet": "alola",
    "slot": 91
  },
  "28:alola": {
    "sheet": "alola",
    "slot": 92
  },
  "37:alola": {
    "sheet": "alola",
    "slot": 93
  },
  "38:alola": {
    "sheet": "alola",
    "slot": 94
  },
  "50:alola": {
    "sheet": "alola",
    "slot": 95
  },
  "51:alola": {
    "sheet": "alola",
    "slot": 96
  },
  "52:alola": {
    "sheet": "alola",
    "slot": 97
  },
  "53:alola": {
    "sheet": "alola",
    "slot": 98
  },
  "74:alola": {
    "sheet": "alola",
    "slot": 99
  },
  "75:alola": {
    "sheet": "alola",
    "slot": 100
  },
  "76:alola": {
    "sheet": "alola",
    "slot": 101
  },
  "88:alola": {
    "sheet": "alola",
    "slot": 102
  },
  "89:alola": {
    "sheet": "alola",
    "slot": 103
  },
  "103:alola": {
    "sheet": "alola",
    "slot": 104
  },
  "105:alola": {
    "sheet": "alola",
    "slot": 105
  },
  "52:galar": {
    "sheet": "galar",
    "slot": 96
  },
  "77:galar": {
    "sheet": "galar",
    "slot": 97
  },
  "78:galar": {
    "sheet": "galar",
    "slot": 98
  },
  "79:galar": {
    "sheet": "galar",
    "slot": 99
  },
  "80:galar": {
    "sheet": "galar",
    "slot": 100
  },
  "83:galar": {
    "sheet": "galar",
    "slot": 101
  },
  "110:galar": {
    "sheet": "galar",
    "slot": 102
  },
  "122:galar": {
    "sheet": "galar",
    "slot": 103
  },
  "144:galar": {
    "sheet": "galar",
    "slot": 104
  },
  "145:galar": {
    "sheet": "galar",
    "slot": 105
  },
  "146:galar": {
    "sheet": "galar",
    "slot": 106
  },
  "199:galar": {
    "sheet": "galar",
    "slot": 107
  },
  "222:galar": {
    "sheet": "galar",
    "slot": 108
  },
  "263:galar": {
    "sheet": "galar",
    "slot": 109
  },
  "264:galar": {
    "sheet": "galar",
    "slot": 110
  },
  "554:galar": {
    "sheet": "galar",
    "slot": 111
  },
  "555:galar": {
    "sheet": "galar",
    "slot": 112
  },
  "562:galar": {
    "sheet": "galar",
    "slot": 113
  },
  "618:galar": {
    "sheet": "galar",
    "slot": 114
  },
  "58:hisui": {
    "sheet": "galar",
    "slot": 115
  },
  "59:hisui": {
    "sheet": "galar",
    "slot": 116
  },
  "100:hisui": {
    "sheet": "galar",
    "slot": 117
  },
  "101:hisui": {
    "sheet": "galar",
    "slot": 118
  },
  "157:hisui": {
    "sheet": "galar",
    "slot": 119
  },
  "211:hisui": {
    "sheet": "galar",
    "slot": 120
  },
  "215:hisui": {
    "sheet": "galar",
    "slot": 121
  },
  "503:hisui": {
    "sheet": "galar",
    "slot": 122
  },
  "549:hisui": {
    "sheet": "galar",
    "slot": 123
  },
  "570:hisui": {
    "sheet": "galar",
    "slot": 124
  },
  "571:hisui": {
    "sheet": "galar",
    "slot": 125
  },
  "628:hisui": {
    "sheet": "galar",
    "slot": 126
  },
  "705:hisui": {
    "sheet": "galar",
    "slot": 127
  },
  "706:hisui": {
    "sheet": "galar",
    "slot": 128
  },
  "713:hisui": {
    "sheet": "galar",
    "slot": 129
  },
  "724:hisui": {
    "sheet": "galar",
    "slot": 130
  },
  "128:paldea": {
    "sheet": "paldea",
    "slot": 120
  },
  "194:paldea": {
    "sheet": "paldea",
    "slot": 121
  }
};

export const spriteSheetVersions: Record<string, string> = {
  "kanto": "e9a6b3c01df0",
  "johto": "5598a713507c",
  "hoenn": "4f2f2737f026",
  "sinnoh": "0db56b7fecca",
  "unova": "43bae6fe562f",
  "kalos": "1d1891d2177e",
  "alola": "af1a0f644082",
  "galar": "120be039691d",
  "paldea": "0b26162018fe"
};
